spring:
  redis:
    host: 192.168.204.156
    port: 6379
    password: root
    database: 0
    lettuce:
      pool:
        # 启动连接池
        enabled: true
        # 最大的空闲连接数量
        max-idle: 8
        # 最小的空闲连接数量
        min-idle: 0
        # 最大活跃连接数量
        max-active: 8
